### ISSUE TITLE
SQL file?

### ISSUE THREAD

**Issue by Thundros** [tehzwen/MultiplayerWebGL#3]
Hi @tehzwen ! First off, I'd like to say EXCELLENT work! Keep up the GREAT work! :)

Secondly, I'd like to know if it's possible to get a copy of the SQL file so I can try this project on my Xampp Server.

Thank you!

**Comment by tehzwen** [comment]
Hey no problem, I can certainly look into providing the sql file with the database schema that I have so far or I can describe what each table contains. Please let me know what works best!

**Comment by Thundros** [comment]
@tehzwen thank you so much! :)  I just need the whole database so this thing works! :)

**Comment by tehzwen** [comment]
Sure thing, I'll add the sql file to the repo after work today if that works.

**Comment by Thundros** [comment]
@tehzwen That's PERFECT, thank you very much! ^_^

**Comment by tehzwen** [comment]
I have uploaded the SQL file into a folder in the root directory called sqlbackups, hopefully this helps with getting postgres setup, I apologize for any random data that is in the tables due to this being a full backup. Do let me know if it works for you and I'll close this issue. If not we can work through it.

**Comment by lukasjenks** [comment]
test
